export const CRAIGSLIST_CONFIG = {
  BASE_URL: 'https://newyork.craigslist.org',
  SEARCH_PATH: '/search/sss',
  RATE_LIMIT: {
    REQUESTS_PER_MINUTE: 10,
    DELAY_BETWEEN_REQUESTS: 6000, // 6 seconds
  },
  SELECTORS: {
    LISTING: 'li.result-row',
    TITLE: '.result-title',
    PRICE: '.result-price',
    LINK: '.result-title',
    DATE: '.result-date',
    LOCATION: '.result-hood',
    IMAGE: '.result-image img',
  },
  CATEGORIES: {
    ALL: 'sss',
    ANTIQUES: 'ata',
    APPLIANCES: 'ppa',
    ARTS_CRAFTS: 'ara',
    ATVS_UTVS_SNOW: 'sna',
    AUTO_PARTS: 'pta',
    AVIONICS: 'ava',
    BABY_KIDS: 'baa',
    BEAUTY_HEALTH: 'haa',
    BIKES: 'bia',
    BOATS: 'boa',
    BOOKS: 'bka',
    BUSINESS: 'bfa',
    CARS_TRUCKS: 'cta',
    CDS_DVDS_VHS: 'ema',
    CELL_PHONES: 'moa',
    CLOTHING: 'cla',
    COLLECTIBLES: 'cba',
    COMPUTERS: 'sya',
    ELECTRONICS: 'ela',
    FARM_GARDEN: 'gra',
    FREE: 'zip',
    FURNITURE: 'fua',
    GARAGE_SALE: 'gms',
    GENERAL: 'foa',
    HEAVY_EQUIP: 'hva',
    HOUSEHOLD: 'hsa',
    JEWELRY: 'jwa',
    MATERIALS: 'maa',
    MOTORCYCLES: 'mca',
    MUSIC_INSTRUMENTS: 'msa',
    PHOTO_VIDEO: 'pha',
    RVS_CAMP: 'rva',
    SPORTING: 'sga',
    TICKETS: 'tia',
    TOOLS: 'tla',
    TOYS_GAMES: 'taa',
    VIDEO_GAMING: 'vga',
    WANTED: 'waa',
    WHEELS_TIRES: 'wta',
  },
} as const; 